### PR TITLE
fix typos, brands and acronyms

### PR DESCRIPTION
**Pull request by ccoVeille**
- **fix typos in code, test and documentation**
- **Fix registered trademark and other acronyms**

### CODE REVIEW

**Comment by ccoVeille** [comment]
No problem. I'll when I have a minute later today.

**Comment by ccoVeille** [comment]
It should be OK now.

**Comment by ccoVeille** [comment]
I recommend using simple tools from time to time, such as 

https://github.com/crate-ci/typos
https://github.com/codespell-project/codespell

More information about them in an old article I made on dev.to

https://dev.to/ccoveille/how-to-fix-typos-in-your-code-for-goods--3c7

**Comment by xhd2015** [comment]
> https://dev.to/ccoveille/how-to-fix-typos-in-your-code-for-goods--3c7

Great, I'll integrate them into the git hooks

**Comment by ccoVeille** [comment]
> > https://dev.to/ccoveille/how-to-fix-typos-in-your-code-for-goods--3c7
> 
> Great, I'll integrate them into the git hooks

I would say this one is the simplest to use 

https://github.com/marketplace/actions/typos-action

**Comment by xhd2015** [comment]
> > > https://dev.to/ccoveille/how-to-fix-typos-in-your-code-for-goods--3c7
> > 
> > 
> > Great, I'll integrate them into the git hooks
> 
> I would say this one is the simplest to use
> 
> https://github.com/marketplace/actions/typos-action

How do you handle false positives? Like these: https://github.com/xhd2015/xgo/actions/runs/8520319809/job/23336201289?pr=24

I'd like `nd` ,`lits`  to remain unchanged

```
Warning: "hae" should be "have".
Warning: "nd" should be "and".
Warning: "ue" should be "use" or "due".
Warning: "nd" should be "and".
Warning: "ue" should be "use" or "due".
Warning: "Lits" should be "List".
Warning: "lits" should be "list".
Warning: "lits" should be "list".
Warning: "lits" should be "list".
Warning: "lits" should be "list".
Warning: "Lits" should be "List".
error: `hae` should be `have`
  --> ./cmd/xgo/patch_compiler.go:166:34
    |
166 |     // go1.19 and under does not hae PGO
    |                                  ^^^
    |
error: `nd` should be `and`
  --> ./patch/debug.go:180:3
    |
180 |   nd := fn.Body[0]
```

**Comment by ccoVeille** [comment]
https://github.com/marketplace/actions/typos-action#false-positives

add a _typos.toml

```toml
[default]
extend-ignore-identifiers-re = [
    "[Ll]its", # Lits is a valid concept here
    "nd",     # short variable I would like to use
]
```

**Comment by xhd2015** [comment]
Thanks, learned a lot

**Pull request merged**
