### PR TITLE
change server domain to 0.0.0.0

### PR DESCRIPTION
**Pull request by tiezhuli001**
change server domain to 0.0.0.0. allow remote ssh connections to access the http address via the ip:port format.

### CODE REVIEW

**Comment by ccoVeille** [comment]
I'm unsure why it was marked as completed while it wasn't merged

**Comment by xhd2015** [comment]
> I'm unsure why it was marked as completed while it wasn't merged

@ccoVeille the author and I have communicated privately and decided we will issue another PR to address this issue.

**Comment by ccoVeille** [comment]
Thanks for giving context

**Comment by xhd2015** [comment]
Thanks for your concerning

**Pull request closed without merging**
